### ISSUE TITLE
Issues compiling DALES

### ISSUE THREAD

**Issue by son-ra** [dalesteam/dales#81] opened 2023-05-17 22:00 UTC
Hi! I have tried to compile DALES using the instructions in the [installation notes](https://github.com/dalesteam/dales/wiki/Installation-notes) both for the Ubuntu system I use and on my local macOS, and neither have successfully compiled. Is there a specific version of gfortran you recommend?

Thank you!

**Comment by jchylik** [comment] 2023-05-17 23:20
> neither have successfully compiled.
But what was the error?
Was it something related to MPI casting?


> Is there a specific version of gfortran you recommend?
No, over the last  4 years, I compiled it on many different gfortran versions.

**Comment by son-ra** [comment] 2023-05-18 00:29
Thank you so much for your response! It does seem to be related to openmpi

```
  The Fortran compiler

    "/admin/software/xenial/pgi/17.5/openmpi-2.1.3/bin/mpif90"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /zeolite/smmrrr/dales/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_f8891/fast && /usr/bin/make  -f CMakeFiles/cmTC_f8891.dir/build.make CMakeFiles/cmTC_f8891.dir/build
    make[1]: Entering directory '/zeolite/smmrrr/dales/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_f8891.dir/testFortranCompiler.f.o
    /admin/software/xenial/pgi/17.5/openmpi-2.1.3/bin/mpif90   -cpp -fimplicit-none -fdefault-real-8 -fdefault-double-8 -march=native -ffree-line-length-none -std=gnu -Werror=implicit-interface  -c /zeolite/smmrrr/dales/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_f8891.dir/testFortranCompiler.f.o
    pgfortran-Error-Unknown switch: -fimplicit-none
    pgfortran-Error-Unknown switch: -fdefault-real-8
    pgfortran-Error-Unknown switch: -fdefault-double-8
    pgfortran-Error-Unknown switch: -march=native
    pgfortran-Error-Unknown switch: -ffree-line-length-none
    pgfortran-Error-Unknown switch: -std=gnu
    pgfortran-Error-Unknown switch: -Werror=implicit-interface
    CMakeFiles/cmTC_f8891.dir/build.make:77: recipe for target 'CMakeFiles/cmTC_f8891.dir/testFortranCompiler.f.o' failed
    make[1]: *** [CMakeFiles/cmTC_f8891.dir/testFortranCompiler.f.o] Error 1
    make[1]: Leaving directory '/zeolite/smmrrr/dales/build/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_f8891/fast' failed
    make: *** [cmTC_f8891/fast] Error 2
```

**Comment by jchylik** [comment] 2023-05-18 11:26
>     pgfortran-Error-Unknown switch: -fimplicit-none
>     pgfortran-Error-Unknown switch: -fdefault-real-8

Wait a second, it says `pgfortran`. Are you are using a PGI  fortran compilier? Never tried them myself, but heard mostly complains about  them. Lot of modern compiler flags are simply not recognised there.


Please try to compile it with GFortran instead.

**Comment by jchylik** [comment] 2023-05-18 18:14
The output directly says what the problem  is: 

> x86_64-apple-darwin13.4.0-gfortran: command not found

i.e. gfortran is either not installed, or installed badly

**Comment by son-ra** [comment] 2023-05-18 19:54
Thank you so much I have gotten this to compile, I appreciate your patience with my novice questions :)

**Comment by son-ra** [comment] 2023-05-18 20:04
For future reference if any other novice fortran users come across this, the issue was that my bash_profile was pointing to `export PATH="/opt/anaconda3/bin:$PATH"` when it needed to point to `export PATH="/usr/local/bin:$PATH"` for find the gfortran compiler.

**Comment by fjansson** [comment] 2023-05-19 12:26
Since the problem is solved, I will close the issue. Thanks Jan for the solution! Ask more if you're stuck again and let us know where the wiki could be more helpful.

**Closed by fjansson** 2023-05-19 12:26 UTC
